### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by benjameep** [nisaacson/pdf-extract#23]
In the README under windows, the link 'pdftotext' http://manifestwebdesign.com/2013/01/09/xpdf-and-poppler-utils-on-windows/  now just redirects to the manifestwebdesign.com homepage.

**Comment by designerx2** [comment]
Stuck at this point and scratching my head about which binary(s) are actually needed.

**Comment by manuvel** [comment]
Any update on the broken link of xpdf????

**Comment by josephrony277** [comment]
Hey guys, 

Download xpdf tools for windows and unzip the file and refer the bin32 folder path which is inside the zip in the system environment variables

![image](https://user-images.githubusercontent.com/2527585/31340016-715fdfb4-ad22-11e7-953b-1396072042cb.png)

It will work!!!!!

**Comment by mcnewbk** [comment]
I have done all of this, but I still get this error: 
Error: spawn pdftotext ENOENT
    at exports._errnoException (util.js:1034:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

Have you found a way around this as well? I have added all the required downloads to my system environment variables as well.

**Comment by josephrony277** [comment]
I have 2 doubts

1. Did you restart the system after updating the environment variables?
2. Did you install pdftotext module after updating the poppler environment variable?

**Comment by mcnewbk** [comment]
@josephrony277 My issue was actually solved by having pdftotext as both a system environment variable and also adding it to the 'path' system environment variable. I had not added it to the actual 'path' variable when I posted this comment. Thanks for your response.
